[package]
name = "blockade"
version = "0.1.0"
authors = ["Joseph Murphy <air.jmurph@gmail.com>"]
license = "MIT"
description = "A wrapper library to interface with the Blockade project"

[dependencies]
